version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mall-mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
    container_name: mall-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  elasticsearch:
    container_name: mall-elasticsearch
    build:
      context: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: elastic/kibana:7.16.2
    container_name: mall-kibana
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: elastic/logstash:7.16.2
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  elasticsearch: