version: '3.9'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
    container_name: mall-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data